# Generated by Django 5.2.6 on 2025-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_qr/'),
        ),
    ]
